name: Release

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew bundleRelease
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          files: |
            app/build/outputs/apk/release/asteroids-${{ github.ref_name }}-release-unsigned.apk